import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

const navItems =[
    {name:"Home",href:"/"},
    {name:"Dashboard",href:"/dashboard"},
    {name:"Login",href:"/login"},
    {name:"Verify",href:"/verify"},
]

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navbar navItems={navItems}/>
        {children}
      </body>
    </html>
  );
}
